### ISSUE TITLE
Feature Request: support of Shelly Plus PM Mini Gen2 power meter

### ISSUE THREAD

**Issue by jfallot** [lukassoo/ShellyExporters#7]
I haven't been able to use any of the available exporters to query my https://shelly-api-docs.shelly.cloud/gen2/Devices/Gen2/ShellyPlusPMMini/ where stats are available in the object https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/PM1#pm1getstatus-example

It would be great to also support that device :)

**Comment by lukassoo** [comment]
Hi,
Sure thing, I'll write an exporter for it 🙂
However, I probably won't be able to do so in the coming weeks since I am currently busy with a project that is nearing its deadline.

If you need the stats as soon as possible then you might need to look for another exporter until I have some time to write it,
Once it's ready for testing I'll let you know.

**Comment by jfallot** [comment]
Here is my contribution, based on the ShellyPlus1PmExporter.
I tested it locally.

**Comment by lukassoo** [comment]
Thanks for the contribution!
I have looked over the changes and everything looks good.

However, I pushed 2 small additional commits before merging.
The default port allocation is something the Prometheus guys track: 
https://github.com/prometheus/prometheus/wiki/Default-port-allocations
I have reserved port 10024 and changed the default port in Program.cs and Dockerfile.
Additionally, a small code cleanup changing EndsWith("/") to EndsWith('/') - using char overload, and changing the method name UpdatePM1Metrics to UpdatePm1Metrics.
Keeps the naming consistent and IDE happy.

I'll update the wiki and upload a docker container soon 🙂
